name: Formatting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master and dev branch
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  formatting-check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format
      run: |
        apt-get update \
        && apt-get install --no-install-recommends -y \
        clang-format-16 \
        && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
        && apt-get clean -y && rm -rf /var/lib/apt/lists/* \
        && mv /usr/bin/clang-format-16 /usr/bin/clang-format
      shell: bash